package br.com.feras.cadastropessoasproducer.validation.input;

public enum PessoaNacionalidade {

  AFGHANISTAN	("Afghanistan", "AF"),
  ALBANIA	("Albania", "AL"),
  ALGERIA	("Algeria", "DZ"),
  AMERICAN_SAMOA	("American Samoa", "AS"),
  ANDORRA	("Andorra", "AD"),
  ANGOLA	("Angola", "AO"),
  ANGUILLA	("Anguilla", "AI"),
  ANTARCTICA	("Antarctica", "AQ"),
  ANTIGUA_AND_BARBUDA	("Antigua and Barbuda", "AG"),
  ARGENTINA	("Argentina", "AR"),
  ARMENIA	("Armenia", "AM"),
  ARUBA	("Aruba", "AW"),
  AUSTRALIA	("Australia", "AU"),
  AUSTRIA	("Austria", "AT"),
  AZERBAIJAN	("Azerbaijan", "AZ"),
  BAHAMAS_THE	("Bahamas (the)", "BS"),
  BAHRAIN	("Bahrain", "BH"),
  BANGLADESH	("Bangladesh", "BD"),
  BARBADOS	("Barbados", "BB"),
  BELARUS	("Belarus", "BY"),
  BELGIUM	("Belgium", "BE"),
  BELIZE	("Belize", "BZ"),
  BENIN	("Benin", "BJ"),
  BERMUDA	("Bermuda", "BM"),
  BHUTAN	("Bhutan", "BT"),
  BOLIVIA	("Bolivia", "BO"),
  BONAIRE_SINT_EUSTATIUS_AND_SABA	("Bonaire, Sint Eustatius and Saba", "BQ"),
  BOSNIA_AND_HERZEGOVINA	("Bosnia and Herzegovina", "BA"),
  BOTSWANA	("Botswana", "BW"),
  BOUVET_ISLAND	("Bouvet Island", "BV"),
  BRAZIL	("Brasil", "BR"),
  BRITISH_INDIAN_OCEAN_TERRITORY ("British Indian Ocean Territory (the)", "IO"),
  BRUNEI_DARUSSALAM	("Brunei Darussalam", "BN"),
  BULGARIA	("Bulgaria", "BG"),
  BURKINA_FASO	("Burkina Faso", "BF"),
  BURUNDI	("Burundi", "BI"),
  CABO_VERDE	("Cabo Verde", "CV"),
  CAMBODIA	("Cambodia", "KH"),
  CAMEROON	("Cameroon", "CM"),
  CANADA	("Canada", "CA"),
  CAYMAN_ISLANDS ("Cayman Islands (the)", "KY"),
  CENTRAL_AFRICAN_REPUBLIC	("Central African Republic (the)", "CF"),
  CHAD	("Chad", "TD"),
  CHILE	("Chile", "CL"),
  CHINA	("China", "CN"),
  CHRISTMAS_ISLAND	("Christmas Island", "CX"),
  COCOS_ISLANDS	("Cocos (Keeling) Islands (the)", "CC"),
  COLOMBIA	("Colombia", "CO"),
  COMOROS ("Comoros (the)", "KM"),
  CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE	("Congo (the Democratic Republic of the)", "CD"),
  CONGO ("Congo (the)", "CG"),
  COOK_ISLANDS ("Cook Islands (the)", "CK"),
  COSTA_RICA	("Costa Rica", "CR"),
  CROATIA	("Croatia", "HR"),
  CUBA	("Cuba", "CU"),
  CURAÇAO	("Curaçao", "CW"),
  CYPRUS	("Cyprus", "CY"),
  CZECHIA ("Czechia (Czech Republic)", "CZ"),
  COTE_D_IVOIRE	("Costa do Marfim", "CI"),
  DENMARK	("Denmark", "DK"),
  DJIBOUTI	("Djibouti", "DJ"),
  DOMINICA	("Dominica", "DM"),
  DOMINICAN_REPUBLIC ("Dominican Republic (the)", "DO"),
  ECUADOR	("Ecuador", "EC"),
  EGYPT	("Egito", "EG"),
  EL_SALVADOR	("El Salvador", "SV"),
  EQUATORIAL_GUINEA	("Equatorial Guinea", "GQ"),
  ERITREA	("Eritrea", "ER"),
  ESTONIA	("Estonia", "EE"),
  ESWATINI	("Eswatini", "SZ"),
  ETHIOPIA	("Ethiopia", "ET"),
  FALKLAND_ISLANDS_MALVINAS	("Falkland Islands (the) [Malvinas]", "FK"),
  FAROE_ISLANDS ("Faroe Islands (the)", "FO"),
  FIJI	("Fiji", "FJ"),
  FINLAND	("Finland", "FI"),
  FRANCE	("France", "FR"),
  FRENCH_GUIANA	("French Guiana", "GF"),
  FRENCH_POLYNESIA	("French Polynesia", "PF"),
  FRENCH_SOUTHERN_TERRITORIES ("French Southern Territories (the)", "TF"),
  GABON	("Gabon", "GA"),
  GAMBIA ("Gambia (the)", "GM"),
  GEORGIA	("Georgia", "GE"),
  GERMANY	("Germany", "DE"),
  GHANA	("Ghana", "GH"),
  GIBRALTAR	("Gibraltar", "GI"),
  GREECE	("Greece", "GR"),
  GREENLAND	("Greenland", "GL"),
  GRENADA	("Grenada", "GD"),
  GUADELOUPE	("Guadeloupe", "GP"),
  GUAM	("Guam", "GU"),
  GUATEMALA	("Guatemala", "GT"),
  GUERNSEY	("Guernsey", "GG"),
  GUINEA	("Guinea", "GN"),
  GUINEA_BISSAU	("Guinea-Bissau", "GW"),
  GUYANA	("Guyana", "GY"),
  HAITI	("Haiti", "HT"),
  HEARD_ISLAND_AND_MCDONALD_ISLANDS	("Heard Island and McDonald Islands", "HM"),
  HOLY_SEE ("Holy See (the)", "VA"),
  HONDURAS	("Honduras", "HN"),
  HONG_KONG	("Hong Kong", "HK"),
  HUNGARY	("Hungary", "HU"),
  ICELAND	("Iceland", "IS"),
  INDIA	("India", "IN"),
  INDONESIA	("Indonesia", "ID"),
  IRAN ("Iran (Islamic Republic of)", "IR"),
  IRAQ	("Iraq", "IQ"),
  IRELAND	("Ireland", "IE"),
  ISLE_OF_MAN	("Isle of Man", "IM"),
  ISRAEL	("Israel", "IL"),
  ITALY	("Italy", "IT"),
  JAMAICA	("Jamaica", "JM"),
  JAPAN	("Japan", "JP"),
  JERSEY	("Jersey", "JE"),
  JORDAN	("Jordan", "JO"),
  KAZAKHSTAN	("Kazakhstan", "KZ"),
  KENYA	("Kenya", "KE"),
  KIRIBATI	("Kiribati", "KI"),
  KOREA_THE_DEMOCRATIC_PEOPLES_REPUBLIC_OF	("Korea (the Democratic People's Republic of)", "KP"),
  KOREA_THE_REPUBLIC_OF	("Korea (the Republic of)", "KR"),
  KUWAIT	("Kuwait", "KW"),
  KYRGYZSTAN	("Kyrgyzstan", "KG"),
  LAO_PEOPLES_DEMOCRATIC_REPUBLIC ("Lao People's Democratic Republic (the)", "LA"),
  LATVIA	("Latvia", "LV"),
  LEBANON	("Lebanon", "LB"),
  LESOTHO	("Lesotho", "LS"),
  LIBERIA	("Liberia", "LR"),
  LIBYA	("Libya", "LY"),
  LIECHTENSTEIN	("Liechtenstein", "LI"),
  LITHUANIA	("Lithuania", "LT"),
  LUXEMBOURG	("Luxembourg", "LU"),
  MACAO	("Macao", "MO"),
  MADAGASCAR	("Madagascar", "MG"),
  MALAWI	("Malawi", "MW"),
  MALAYSIA	("Malaysia", "MY"),
  MALDIVES	("Maldives", "MV"),
  MALI	("Mali", "ML"),
  MALTA	("Malta", "MT"),
  MARSHALL_ISLANDS ("Marshall Islands (the)", "MH"),
  MARTINIQUE	("Martinique", "MQ"),
  MAURITANIA	("Mauritania", "MR"),
  MAURITIUS	("Mauritius", "MU"),
  MAYOTTE	("Mayotte", "YT"),
  MEXICO	("Mexico", "MX"),
  MICRONESIA ("Micronesia (Federated States of)", "FM"),
  MOLDOVA ("Moldova (the Republic of)", "MD"),
  MONACO	("Monaco", "MC"),
  MONGOLIA	("Mongolia", "MN"),
  MONTENEGRO	("Montenegro", "ME"),
  MONTSERRAT	("Montserrat", "MS"),
  MOROCCO	("Morocco", "MA"),
  MOZAMBIQUE	("Mozambique", "MZ"),
  MYANMAR	("Myanmar", "MM"),
  NAMIBIA	("Namibia", "NA"),
  NAURU	("Nauru", "NR"),
  NEPAL	("Nepal", "NP"),
  NETHERLANDS ("Netherlands (the)", "NL"),
  NEW_CALEDONIA	("New Caledonia", "NC"),
  NEW_ZEALAND	("New Zealand", "NZ"),
  NICARAGUA	("Nicaragua", "NI"),
  NIGER ("Niger (the)", "NE"),
  NIGERIA	("Nigeria", "NG"),
  NIUE	("Niue", "NU"),
  NORFOLK_ISLAND	("Norfolk Island", "NF"),
  NORTH_MACEDONIA	("North Macedonia", "MK"),
  NORTHERN_MARIANA_ISLANDS ("Northern Mariana Islands (the)", "MP"),
  NORWAY	("Norway", "NO"),
  OMAN	("Oman", "OM"),
  PAKISTAN	("Pakistan", "PK"),
  PALAU	("Palau", "PW"),
  PALESTINE ("Palestine, State of", "PS"),
  PANAMA	("Panama", "PA"),
  PAPUA_NEW_GUINEA	("Papua New Guinea", "PG"),
  PARAGUAY	("Paraguay", "PY"),
  PERU	("Peru", "PE"),
  PHILIPPINES ("Philippines (the)", "PH"),
  PITCAIRN	("Pitcairn", "PN"),
  POLAND	("Poland", "PL"),
  PORTUGAL	("Portugal", "PT"),
  PUERTO_RICO	("Puerto Rico", "PR"),
  QATAR	("Qatar", "QA"),
  ROMANIA	("Romania", "RO"),
  RUSSIAN_FEDERATION ("Russian Federation (the)", "RU"),
  RWANDA	("Rwanda", "RW"),
  RÉUNION	("Réunion", "RE"),
  SAINT_BARTHÉLEMY	("Saint Barthélemy", "BL"),
  SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA	("Saint Helena, Ascension and Tristan da Cunha", "SH"),
  SAINT_KITTS_AND_NEVIS	("Saint Kitts and Nevis", "KN"),
  SAINT_LUCIA	("Saint Lucia", "LC"),
  SAINT_MARTIN ("Saint Martin (French part)", "MF"),
  SAINT_PIERRE_AND_MIQUELON	("Saint Pierre and Miquelon", "PM"),
  SAINT_VINCENT_AND_THE_GRENADINES	("Saint Vincent and the Grenadines", "VC"),
  SAMOA	("Samoa", "WS"),
  SAN_MARINO	("San Marino", "SM"),
  SAO_TOME_AND_PRINCIPE	("Sao Tome and Principe", "ST"),
  SAUDI_ARABIA	("Saudi Arabia", "SA"),
  SENEGAL	("Senegal", "SN"),
  SERBIA	("Serbia", "RS"),
  SEYCHELLES	("Seychelles", "SC"),
  SIERRA_LEONE	("Sierra Leone", "SL"),
  SINGAPORE	("Singapore", "SG"),
  SINT_MAARTEN 	("Sint Maarten (Dutch part)", "SX"),
  SLOVAKIA	("Slovakia", "SK"),
  SLOVENIA	("Slovenia", "SI"),
  SOLOMON_ISLANDS	("Solomon Islands", "SB"),
  SOMALIA	("Somalia", "SO"),
  SOUTH_AFRICA	("South Africa", "ZA"),
  SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS	("South Georgia and the South Sandwich Islands", "GS"),
  SOUTH_SUDAN	("South Sudan", "SS"),
  SPAIN	("Spain", "ES"),
  SRI_LANKA	("Sri Lanka", "LK"),
  SUDAN ("Sudan (the)", "SD"),
  SURINAME	("Suriname", "SR"),
  SVALBARD_AND_JAN_MAYEN	("Svalbard and Jan Mayen", "SJ"),
  SWEDEN	("Sweden", "SE"),
  SWITZERLAND	("Switzerland", "CH"),
  SYRIAN_ARAB_REPUBLIC ("Syrian Arab Republic (the)", "SY"),
  TAIWAN	("Taiwan (Province of China)", "TW"),
  TAJIKISTAN	("Tajikistan", "TJ"),
  TANZANIA ("Tanzania, the United Republic of", "TZ"),
  THAILAND	("Thailand", "TH"),
  TIMOR_LESTE	("Timor-Leste", "TL"),
  TOGO	("Togo", "TG"),
  TOKELAU	("Tokelau", "TK"),
  TONGA	("Tonga", "TO"),
  TRINIDAD_AND_TOBAGO	("Trinidad and Tobago", "TT"),
  TUNISIA	("Tunisia", "TN"),
  TURKEY	("Turkey", "TR"),
  TURKMENISTAN	("Turkmenistan", "TM"),
  TURKS_AND_CAICOS_ISLANDS ("Turks and Caicos Islands (the)", "TC"),
  TUVALU	("Tuvalu", "TV"),
  UGANDA	("Uganda", "UG"),
  UKRAINE	("Ukraine", "UA"),
  UNITED_ARAB_EMIRATES ("United Arab Emirates (the)", "AE"),
  UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND ("United Kingdom of Great Britain and Northern Ireland", "GB"),
  UNITED_STATES_MINOR_OUTLYING_ISLANDS ("United States Minor Outlying Islands", "UM"),
  UNITED_STATES_OF_AMERICA ("United States of America", "US"),
  URUGUAY	("Uruguay", "UY"),
  UZBEKISTAN	("Uzbekistan", "UZ"),
  VANUATU	("Vanuatu", "VU"),
  VENEZUELA ("Venezuela (Bolivarian Republic of)", "VE"),
  VIET_NAM	("Viet Nam", "VN"),
  VIRGIN_ISLANDS_BRITISH	("Virgin Islands (British)", "VG"),
  VIRGIN_ISLANDS("Virgin Islands (U.S.)", "VI"),
  WALLIS_AND_FUTUNA	("Wallis and Futuna", "WF"),
  WESTERN_SAHARA	("Western Sahara*", "EH"),
  YEMEN	("Yemen", "YE"),
  ZAMBIA	("Zambia", "ZM"),
  ZIMBABWE	("Zimbabwe", "ZW"),
  ALAND_ISLANDS	("Aland Islands", "AX");

  private String nome;
  private String sigla;

  PessoaNacionalidade(String nome, String sigla) {
    this.nome = nome;
    this.sigla = sigla;
  }

  public static boolean isNacionalidadeValida(String nomePais) {
    for (PessoaNacionalidade pais : PessoaNacionalidade.values()) {
      if (pais.nome.equalsIgnoreCase(nomePais) || pais.sigla.equalsIgnoreCase(nomePais)) {
        return true;
      }
    }
    return false;
  }
}
